apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
spec:
  destination:
    server: https://34.136.0.179
    namespace: sample-ns
  project: default
  source:
    path: docker/
    repoURL: https://github.com/chaithukrissh/SAM-project.git
    targetRevision: HEAD

